#!/usr/bin/env python3
"""Root-owned deployment helper. Never include deploy-writable Nginx code.

Install at /usr/local/sbin/minicms-redirects, owned by root, mode 0755.
Optional /etc/minicms-deploy.json: {"web_root": "/srv/www"} (root-owned).

Two files of the live release become Nginx rules here, after validation:
  redirects.json  old path -> new path, as permanent redirects;
  outbound.json   product id -> partner link, as the 302 that /go/<id>/ answers
                  (nested in the vhost's /go/ location, which logs the click).
"""
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

PRODUCT = re.compile(r'[A-Za-z0-9_-]{1,100}')
# A partner link must sit inside a quoted Nginx string: only the characters a
# URL is made of, without a quote, a backslash, a space, braces, or the dollar
# sign Nginx would read as a variable.
PARTNER_URL = re.compile(r"https?://[A-Za-z0-9.-]+(?::[0-9]{1,5})?(?:[/?#][A-Za-z0-9._~%!&'()*+,;=:@/?#\[\]-]*)?")


def render(mapping):
    if mapping == []:
        mapping = {}
    if not isinstance(mapping, dict) or len(mapping) > 10000:
        raise ValueError('Invalid redirect map')
    pattern = re.compile(r'^/(?:[A-Za-z0-9_-]+/)*$')
    for old, new in mapping.items():
        if not isinstance(old, str) or not isinstance(new, str) or not pattern.fullmatch(old) or not pattern.fullmatch(new):
            raise ValueError('Invalid redirect path')
    lines = ['# Generated by root-owned minicms-redirects']
    for old, new in sorted(mapping.items()):
        seen = {old}
        while new in mapping:
            if new in seen:
                raise ValueError('Redirect cycle')
            seen.add(new)
            new = mapping[new]
        lines.append(f'location = {old} {{ return 301 {new}$is_args$args; }}')
    return '\n'.join(lines) + '\n'


def render_outbound(mapping):
    """Partner links by product. Unlike a redirect map this never refuses as a
    whole: the release carries its own /go/<id>/ page for every link, so a link
    left out here still works, while keeping the previous rules would send
    readers to a link the release no longer has."""
    lines = ['# Generated by root-owned minicms-redirects']
    if not isinstance(mapping, dict) or len(mapping) > 1000:
        return '\n'.join(lines) + '\n'
    for product, url in sorted(mapping.items(), key=lambda item: str(item[0])):
        if not isinstance(product, str) or not PRODUCT.fullmatch(product):
            continue
        if not isinstance(url, str) or len(url) > 2000 or not PARTNER_URL.fullmatch(url):
            continue
        lines.append(f'location = /go/{product}/ {{ return 302 "{url}"; }}')
    return '\n'.join(lines) + '\n'


def apply(domain):
    if not re.fullmatch(r'[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?', domain) or '..' in domain:
        raise ValueError('Invalid domain')
    settings = Path('/etc/minicms-deploy.json')
    root = Path(json.loads(settings.read_text())['web_root'] if settings.exists() else '/srv/www').resolve()

    def source(name):
        found = (root / domain / 'current' / name).resolve()
        if root not in found.parents or (found.exists() and found.stat().st_size > 2_000_000):
            raise ValueError('Invalid redirect source')
        return found

    redirects, outbound = source('redirects.json'), source('outbound.json')
    # Old releases predate redirect manifests; activating one must clear newer redirects.
    rules = render(json.loads(redirects.read_text()) if redirects.exists() else {})
    try:
        links = render_outbound(json.loads(outbound.read_text()) if outbound.exists() else {})
    except ValueError:
        # Not JSON at all: no 302s, the release's own pages answer.
        links = render_outbound({})
    targets = [
        (Path('/etc/nginx/aigf-redirects') / domain / 'redirects.conf', rules),
        (Path('/etc/nginx/aigf-outbound') / domain / 'outbound.conf', links),
    ]
    previous = {}
    for target, _ in targets:
        target.parent.mkdir(mode=0o755, parents=True, exist_ok=True)
        previous[target] = target.read_bytes() if target.exists() else None
    # Nothing changed: no rewrite, no reload. Convergence calls this every run.
    if all(previous[target] == body.encode() for target, body in targets):
        return
    try:
        for target, body in targets:
            fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=domain + '-', suffix='.tmp')
            try:
                with os.fdopen(fd, 'w') as stream:
                    stream.write(body)
                os.chmod(tmp, 0o644)
                os.replace(tmp, target)
            finally:
                Path(tmp).unlink(missing_ok=True)
        subprocess.run(['/usr/sbin/nginx', '-t'], check=True)
        subprocess.run(['/usr/bin/systemctl', 'reload', 'nginx'], check=True)
    except Exception:
        for target, _ in targets:
            if previous[target] is None:
                target.unlink(missing_ok=True)
            else:
                target.write_bytes(previous[target])
        raise


if __name__ == '__main__':
    if len(sys.argv) != 2 or os.geteuid() != 0:
        sys.exit('Usage (root): minicms-redirects DOMAIN')
    try:
        import fcntl
        # Serialize Nginx validation/reload even when two domains deploy at once.
        with open('/run/minicms-redirects.lock', 'w') as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            apply(sys.argv[1])
    except Exception as error:
        sys.exit(str(error))
