#!/usr/bin/env python3
"""Root-owned deployment helper. Never include deploy-writable Nginx code.

Install at /usr/local/sbin/minicms-redirects, owned by root, mode 0755.
Optional /etc/minicms-deploy.json: {"web_root": "/srv/www"} (root-owned).
"""
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile


def render(mapping):
    if mapping == []:
        mapping = {}
    if not isinstance(mapping, dict) or len(mapping) > 10000:
        raise ValueError('Invalid redirect map')
    pattern = re.compile(r'^/(?:[A-Za-z0-9_-]+/)*$')
    for old, new in mapping.items():
        if not isinstance(old, str) or not isinstance(new, str) or not pattern.fullmatch(old) or not pattern.fullmatch(new):
            raise ValueError('Invalid redirect path')
    lines = ['# Generated by root-owned minicms-redirects']
    for old, new in sorted(mapping.items()):
        seen = {old}
        while new in mapping:
            if new in seen:
                raise ValueError('Redirect cycle')
            seen.add(new)
            new = mapping[new]
        lines.append(f'location = {old} {{ return 301 {new}$is_args$args; }}')
    return '\n'.join(lines) + '\n'


def apply(domain):
    if not re.fullmatch(r'[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?', domain) or '..' in domain:
        raise ValueError('Invalid domain')
    settings = Path('/etc/minicms-deploy.json')
    root = Path(json.loads(settings.read_text())['web_root'] if settings.exists() else '/srv/www').resolve()
    source = (root / domain / 'current' / 'redirects.json').resolve()
    if root not in source.parents or (source.exists() and source.stat().st_size > 2_000_000):
        raise ValueError('Invalid redirect source')
    # Old releases predate redirect manifests; activating one must clear newer redirects.
    body = render(json.loads(source.read_text()) if source.exists() else {})
    directory = Path('/etc/nginx/aigf-redirects') / domain
    directory.mkdir(mode=0o755, parents=True, exist_ok=True)
    target = directory / 'redirects.conf'
    previous = target.read_bytes() if target.exists() else None
    # Nothing changed: no rewrite, no reload. Convergence calls this every run.
    if previous == body.encode():
        return
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=domain + '-', suffix='.tmp')
    try:
        with os.fdopen(fd, 'w') as stream:
            stream.write(body)
        os.chmod(tmp, 0o644)
        os.replace(tmp, target)
        subprocess.run(['/usr/sbin/nginx', '-t'], check=True)
        subprocess.run(['/usr/bin/systemctl', 'reload', 'nginx'], check=True)
    except Exception:
        if previous is None:
            target.unlink(missing_ok=True)
        else:
            target.write_bytes(previous)
        raise
    finally:
        Path(tmp).unlink(missing_ok=True)


if __name__ == '__main__':
    if len(sys.argv) != 2 or os.geteuid() != 0:
        sys.exit('Usage (root): minicms-redirects DOMAIN')
    try:
        import fcntl
        # Serialize Nginx validation/reload even when two domains deploy at once.
        with open('/run/minicms-redirects.lock', 'w') as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            apply(sys.argv[1])
    except Exception as error:
        sys.exit(str(error))
