<?php

declare(strict_types=1);

namespace AiGf\Tools;

use Symfony\Component\Yaml\Yaml;

/**
 * Builds the cross-GEO artefacts a single-GEO Cecil build cannot know about:
 *
 *   network.geos  — registry of every enabled GEO (used by templates and tooling)
 *   hreflang      — translation_key => list of {geo, hreflang, url}
 *
 * The result is written to .cecil/generated/network.yml and passed to every
 * build as an extra configuration layer, so `site.hreflang` is available in Twig.
 * The file is generated, never committed (see .gitignore).
 */
final class Prepare
{
    public const OUTPUT = '.cecil/generated/network.yml';

    /**
     * @return array{geos: int, keys: int, file: string}
     */
    public static function run(?array $codes = null): array
    {
        $codes = $codes ?? Network::codes(true);
        $xDefault = (string) (Network::presets()['x_default'] ?? 'us');

        $geos = [];
        $hreflang = [];

        foreach ($codes as $code) {
            $geo = Network::geo($code);
            $geos[$code] = [
                'code'     => $code,
                'name'     => $geo['geo']['name'] ?? strtoupper($code),
                'hreflang' => $geo['geo']['hreflang'] ?? $code,
                'language' => $geo['language'] ?? 'en',
                'locale'   => $geo['languages'][0]['locale'] ?? 'en_US',
                'baseurl'  => Network::baseUrl($code),
                'host'     => Network::host($code),
                'currency' => $geo['geo']['currency']['code'] ?? null,
            ];

            foreach (self::indexableEntries($code) as $key => $url) {
                $hreflang[$key][] = [
                    'geo'       => $code,
                    'hreflang'  => (string) ($geo['geo']['hreflang'] ?? $code),
                    'url'       => $url,
                    'x_default' => $code === $xDefault,
                ];
            }
        }

        ksort($hreflang);

        $payload = [
            'network' => [
                'x_default' => $xDefault,
                'geos'      => $geos,
            ],
            'hreflang' => $hreflang,
        ];

        $file = Network::path(...explode('/', self::OUTPUT));
        if (!is_dir(\dirname($file))) {
            mkdir(\dirname($file), 0o777, true);
        }
        file_put_contents(
            $file,
            "# Generated by scripts/prepare — do not edit, do not commit.\n"
            . Yaml::dump($payload, 6, 2)
        );

        return ['geos' => \count($geos), 'keys' => \count($hreflang), 'file' => $file];
    }

    /**
     * translation_key => absolute URL, for pages that are actually indexable.
     *
     * @return array<string,string>
     */
    private static function indexableEntries(string $code): array
    {
        $pages = ContentScanner::scan($code);
        $entries = [];

        foreach ($pages as $page) {
            $fm = $page['front_matter'];
            if (($fm['status'] ?? 'published') !== 'published') {
                continue;
            }
            if (($fm['indexing']['index'] ?? true) === false) {
                continue;
            }
            if (isset($fm['canonical']['url'])) {
                continue; // canonicalised elsewhere: not an hreflang target
            }
            $key = (string) ($fm['translation_key'] ?? $page['id']);
            $entries[$key] = $page['url'];
        }

        // section index pages Cecil generates on the fly
        foreach (ContentScanner::generatedSections($code, $pages) as $section => $info) {
            $entries[$section] = $entries[$section] ?? $info['url'];
        }

        return $entries;
    }
}
