<?php

declare(strict_types=1);

/**
 * scripts/dev <geo> [--port=8000] [--no-drafts]
 *
 * Local preview with live reload. Drafts and pages in review ARE rendered here
 * (and only here) so editors and reviewers can see work in progress.
 */

require __DIR__ . '/../vendor/autoload.php';

use AiGf\Tools\Cli;
use AiGf\Tools\ContentValidator;
use AiGf\Tools\Network;
use AiGf\Tools\Prepare;

[$args, $options] = Cli::parse($argv);

if ($args === []) {
    Cli::error('Usage: scripts/dev <geo> [--port=8000] [--no-drafts]');
    Cli::info('Available GEOs: ' . implode(', ', Network::codes(false)));
    exit(1);
}

$code = Cli::resolveGeos($args)[0];
Prepare::run();

$result = (new ContentValidator())->validate($code);
Cli::report($result);
if ($result['errors'] !== []) {
    Cli::warn('Content errors above would fail a production build.');
}

// `cecil serve` has no --output option, so the preview output directory is
// passed as one more configuration layer.
$devConfig = '.cecil/generated/dev-' . $code . '.yml';
$devConfigPath = Network::path(...explode('/', $devConfig));
if (!is_dir(\dirname($devConfigPath))) {
    mkdir(\dirname($devConfigPath), 0o777, true);
}
file_put_contents($devConfigPath, "# Generated by scripts/dev — local preview only.\noutput:\n  dir: dist/_dev/$code\n");

$command = [
    \PHP_BINARY,
    Network::path('vendor', 'cecil', 'cecil', 'bin', 'cecil'),
    'serve',
    '--config=' . Network::buildConfig($code) . ',' . Prepare::OUTPUT . ',' . $devConfig,
    '--port=' . (string) ($options['port'] ?? '8000'),
    '--incremental',
];
if (empty($options['no-drafts'])) {
    $command[] = '--drafts';
}

Cli::title(\sprintf('Serving %s on http://localhost:%s', strtoupper($code), (string) ($options['port'] ?? '8000')));
Cli::info('Press Ctrl+C to stop.');

$process = proc_open($command, [], $pipes, Network::root());
exit(\is_resource($process) ? proc_close($process) : 1);
