<?php

declare(strict_types=1);

/**
 * scripts/redirect-config [--enable=go.example.com] [--disable]
 *
 * Generates the affiliate redirect service:
 *
 *     https://go.example.com/<product>/<geo>  ->  302  ->  partner URL
 *
 * It is not an application — it is an Nginx `map` built from data/affiliates/,
 * so the production origin stays static-only. Two things it buys you:
 *
 *   1. changing a partner link becomes a config deploy instead of a rebuild of
 *      every page that mentions the product;
 *   2. all monetised clicks land in one access log, per product and per GEO.
 *
 * --enable writes `affiliate.redirect_base` into config/common.yml, after which
 * every CTA in the network points at the redirect host on the next build.
 */

require __DIR__ . '/../vendor/autoload.php';

use AiGf\Tools\Cli;
use AiGf\Tools\Network;

[$args, $options] = Cli::parse($argv);

$commonFile = Network::path('config', 'common.yml');
$common = file_get_contents($commonFile);
if ($common === false) {
    Cli::error('Cannot read config/common.yml');
    exit(1);
}

/* ------------------------------------------------- enable / disable switch */

if (isset($options['enable']) || !empty($options['disable'])) {
    $host = !empty($options['disable']) ? '' : trim((string) $options['enable'], "/ \t");
    if ($host !== '' && !preg_match('/^[a-z0-9.-]+\.[a-z]{2,}$/i', $host)) {
        Cli::error(\sprintf('"%s" does not look like a hostname (expected e.g. go.example.com).', $host));
        exit(1);
    }
    $value = $host === '' ? "''" : "'https://" . $host . "'";
    $updated = preg_replace('/^(\s*redirect_base:).*$/m', '$1 ' . $value, $common, 1);
    if ($updated === null || $updated === $common) {
        Cli::error('Could not find `redirect_base:` in config/common.yml — add it under `affiliate:`.');
        exit(1);
    }
    file_put_contents($commonFile, $updated);
    $common = $updated;
    Cli::ok($host === ''
        ? 'Redirect service disabled: links go straight to the partner again (rebuild to apply).'
        : \sprintf('Redirect service enabled: https://%s (rebuild to apply).', $host));
}

/* ------------------------------------------------------------- generation */

$redirectBase = (string) (Network::common()['affiliate']['redirect_base'] ?? '');
// Network::common() is cached from before the rewrite above, so re-read it.
if (preg_match('/^\s*redirect_base:\s*\'?([^\'\n]*)\'?\s*$/m', $common, $m)) {
    $redirectBase = trim($m[1]);
}

if ($redirectBase === '') {
    Cli::info('Redirect service is off (affiliate.redirect_base is empty).');
    Cli::info('Enable it with:  ./scripts/redirect-config --enable=go.yourdomain.com');
    exit(0);
}

$redirectHost = (string) parse_url($redirectBase, \PHP_URL_HOST);
if ($redirectHost === '') {
    Cli::error(\sprintf('affiliate.redirect_base is not a valid URL: %s', $redirectBase));
    exit(1);
}

$geos = Network::codes(true);
$affiliates = Network::affiliates();

// Unknown or retired links land on the x-default market rather than nowhere.
$xDefault = (string) (Network::presets()['x_default'] ?? 'us');
$fallback = Network::baseUrl(\in_array($xDefault, $geos, true) ? $xDefault : ($geos[0] ?? 'us'));

$entries = [];
$missing = [];
foreach ($affiliates as $productId => $affiliate) {
    foreach ($geos as $geo) {
        $url = $affiliate['geo'][$geo]['url'] ?? $affiliate['default'] ?? null;
        if (empty($url)) {
            $missing[] = $productId . '/' . $geo;
            continue;
        }
        $entries['/' . $productId . '/' . $geo] = (string) $url;
    }
}

if ($entries === []) {
    Cli::error('No affiliate destinations found in data/affiliates/.');
    exit(1);
}

$snippetsDir = Network::path('infra', 'nginx', 'snippets');
$sitesDir = Network::path('infra', 'nginx', 'sites');
foreach ([$snippetsDir, $sitesDir] as $dir) {
    if (!is_dir($dir)) {
        mkdir($dir, 0o777, true);
    }
}

/* map: goes in the http{} context, hence a snippet rather than a vhost */
$map = "# GENERATED by scripts/redirect-config — do not edit on the server.\n"
    . "# <product>/<geo> -> partner URL. Unknown paths fall back to the network homepage.\n"
    . "map \$uri \$aigf_affiliate {\n"
    . \sprintf("    default \"%s\";\n", $fallback);
foreach ($entries as $path => $url) {
    // Values are quoted: partner URLs routinely contain "&" and may contain ";".
    // Both with and without a trailing slash, so a stray slash still resolves.
    $map .= \sprintf("    \"%s\"  \"%s\";\n", $path, $url);
    $map .= \sprintf("    \"%s/\" \"%s\";\n", $path, $url);
}
$map .= "}\n";
file_put_contents($snippetsDir . \DIRECTORY_SEPARATOR . 'affiliate-map.conf', $map);

/* vhost */
$vhost = <<<CONF
# Affiliate redirect service — GENERATED by scripts/redirect-config.
#
# https://{$redirectHost}/<product>/<geo>  ->  302  ->  partner URL
#
# Destinations come from /etc/nginx/snippets/aigf-affiliate-map.conf, which is
# regenerated from data/affiliates/ and deployed like any other config. There is
# no application and no state here.

server {
    listen 80;
    listen [::]:80;
    server_name {$redirectHost};

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://{$redirectHost}\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name {$redirectHost};

    ssl_certificate     /etc/letsencrypt/live/{$redirectHost}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{$redirectHost}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    # This host must never be indexed: it only emits redirects.
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\\nDisallow: /\\n";
    }

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 "ok\\n";
    }

    # 302, never 301: destinations change and must not be cached forever.
    location / {
        return 302 \$aigf_affiliate;
    }

    access_log /var/log/nginx/{$redirectHost}.access.log;
    error_log  /var/log/nginx/{$redirectHost}.error.log warn;
}

CONF;

file_put_contents($sitesDir . \DIRECTORY_SEPARATOR . $redirectHost . '.conf', $vhost);

Cli::ok(\sprintf('%d redirect(s) for %d product(s) x %d GEO(s)', \count($entries), \count($affiliates), \count($geos)));
Cli::ok('infra/nginx/snippets/affiliate-map.conf');
Cli::ok('infra/nginx/sites/' . $redirectHost . '.conf');

foreach (array_unique($missing) as $gap) {
    Cli::warn(\sprintf('No destination for %s — those clicks fall back to the network homepage.', $gap));
}

Cli::title('Install / update on the server');
Cli::info('rsync -az infra/nginx/snippets/affiliate-map.conf root@VPS:/etc/nginx/snippets/aigf-affiliate-map.conf');
Cli::info('rsync -az infra/nginx/sites/' . $redirectHost . '.conf root@VPS:/etc/nginx/sites-available/');
Cli::info('ssh root@VPS "ln -sf /etc/nginx/sites-available/' . $redirectHost . '.conf /etc/nginx/sites-enabled/ && nginx -t && systemctl reload nginx"');
Cli::info('');
Cli::info('The map is included from nginx.conf (infra/server-setup.sh does this).');
Cli::info('On a server provisioned earlier, add once inside http{}:');
Cli::info('    include /etc/nginx/snippets/aigf-affiliate-map.conf;');
